### ISSUE TITLE
Database Setup/Connection

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Backend#1]
Database needs to bet setup, which entails that we will need a host for this database.  Connection/API needs to be established as well for ease of use.

**Comment by SwipeX** [comment]
To be more specific, we are going to be provided an Azure host machine from eMoney.  This still needs to occur.

**Comment by PepperInsure** [comment]
How do we connect to the server?

I tried connecting using visual studio but it didn't work even when using the given username and password.

**Comment by SwipeX** [comment]
Currently there is nothing setup to connect to (besides RDP).  We need to setup a SQL database of choice, (either SQL Server OR MYSQL).  Then we can connect to the database for insertion, quereies, ect.

**Comment by hermetic-charm** [comment]
Due to time constraints and a possible slow response time in getting a license for MS SSMS, it might make sense to just go ahead with MYSQL.  I believe @Trevski13 mentioned he would be willing to set up MYSQL on our Azure instance if we decide to go that route.

**Comment by Trevski13** [comment]
I did indeed say that, so unless anyone has an objection I guess I'll start setting it up tonight.  Even if it's not the same as what we'll use in the end its only a few functions we'll have to modify to get it working with the alternate database.

**Comment by PepperInsure** [comment]
Should have specified in my commit, but the code that actually connects to a database is Form1.cs. It connects at this point to the server specified in a previous email.

**Comment by PepperInsure** [comment]
Also, I've been informed that some of the backend has been done already. I don't know the extent of it because none of it has been committed, but it would make sense to not duplicate effort on the same tasks. What do we have done, and what do we have left to do for the backend?

**Comment by SwipeX** [comment]
@PepperInsure - In order to follow Agile principles, you should select a task from the issues list (that may need to be populated if it has not been adressed).  These tasks should be small, you so can close the issue as soon as you complete it, or at least update the issue with where the current code stands. (And possibly tag the last commit #).

**Comment by raserva** [comment]
we have only the most basic setup right now, and it is all pushed. push
your changes, and i plan on getting it working tonight with no filtering
algorithms

**Comment by raserva** [comment]
Why are there 2 projects in out backend github repo? The connection stuff
should be included in our API

**Comment by PepperInsure** [comment]
I had no idea that anything was happening in the backend and this ticket was up, so I put a little something to connect. If you can already connect to a database, feel free to delete it.

**Comment by Trevski13** [comment]
Install of Microsoft SQL server is in progress, should be done shortly.

**Comment by raserva** [comment]
great

**Comment by raserva** [comment]
Hey trevor is this completed?

**Comment by Trevski13** [comment]
It is indeed setup.  Also the current data we have has been put in the relevant tables.

Do we want to make a specific account + credentials for our program to use for accessing the SQL database?  If so, I'll add one.

**Comment by hermetic-charm** [comment]
Is this pulling from the DB on our server now?

**Comment by raserva** [comment]
no. how do i deploy to our server?

**Comment by raserva** [comment]
Done
