### ISSUE TITLE
Identify Cases 

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Backend#2]
We need to define what cases may present themselves and how we will chose to handle them.   Such as a duplicate entry or inconsistent data.

**Comment by PepperInsure** [comment]
In mySQL foreign keys and primary keys generally handle it. I don't know exactly how what we're using might handle it. Is there a TRIGGER keyword? Inconsistent data can either be taken away or just left there. When queries go through just make sure the relevant parts are not selected.

**Comment by SwipeX** [comment]
Generally we want to leave the database as clean and minimal as possible.  So the C# backend application needs to do its best at removing the unused data.  Duplicates will also do much better being solved in the backend application since we are exporting to JSON and not polling the database consistently.

**Comment by raserva** [comment]
conference rooms, multiples
