### ISSUE TITLE
Define Hierarchy

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Backend#3]
We need to identify the issues and start to create solutions for them with code in mind.  This will likely manifest itself in some sort of visual diagram, but may also include written planning as well.

**Comment by SwipeX** [comment]
Keep in mind this is not the Mock-Design, however it is an estimation of a relational model/database which is according to the data we have been given to this point.

**Comment by raserva** [comment]
Wrote Class and Sequence UML diagrams
