### ISSUE TITLE
Relational Model

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Backend#4]
We need to determine a relational model for all of the data to be encapsulated in.  This should be shown in a diagram at the surface ref #3 .  We need to ensure that queries are simple and are bottomed out to an API call level.  It may also be smart to create serializable objects in C# for these relations so that I/O operations can occur smoothly.

**Comment by SwipeX** [comment]
@raserva has basically finished this, and as long as we have the JSON format completed, this can be closed with confirmation from @mgriner.

**Comment by hermetic-charm** [comment]
From my understanding @raserva has the back-end JSON formatted such that each top-level element is keyed by the unique pair of switch and port names and underneath each of these top level elements is a set of elements containing relevant user information for that switch/port pair.  As long as we are all on the same page I think it is okay to close this.

**Comment by raserva** [comment]
Btw- i've created some start code for the C# API, and i will be working to
get a prototype up soon

**Comment by raserva** [comment]
@mgriner - here is the example JSON in the form that will be returned by
the API.

Can also be found here:
https://github.com/CISC-475-Team-2/Backend/blob/master/API/SeatingChartAPI/SeatingChartAPI/App_Data/SeatingJSON.txt

On Wed, Oct 28, 2015 at 5:05 PM, mgriner notifications@github.com wrote:

> From my understanding @raserva https://github.com/raserva has the
> back-end JSON formatted such that each top-level element is keyed by the
> unique pair of switch and port names and underneath each of these top level
> elements is a set of elements containing relevant user information for that
> switch/port pair. As long as we are all on the same page I think it is okay
> to close this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CISC-475-Team-2/Backend/issues/4#issuecomment-151989954
> .

﻿{
    "emaswitch00":{
        "ports":[
            "A1":{
                "firstName":"John",
                "lastName":"Doe",
                "userName":"jdoe",
                "city":"Newark",
                "department":"IT",
                "email":"jdoe@email.com"
            },
            "A2":{
                "firstName":"Jane",
                "lastName":"Doe",
                "userName":"doej",
                "city":"Newark",
                "department":"Marketing",
                "email":"doej@email.com"
            }
        ]
    },
    "emaswitch01":{
        "ports":[
            "B1":{
                "firstName":"Ryan",
                "lastName":"Serva",
                "userName":"rserva",
                "city":"Newark",
                "department":"Software",
                "email":"rserva@email.com"
            },
        ]
    }
}

**Comment by hermetic-charm** [comment]
@raserva This looks good to me, but two notes:

First, I think the array elements in the ports array have to be wrapped in curly braces, you can always validate at http://jsonlint.com/

Second, If you check Agent_NetworkSwitch.csv in the data package they sent us it looks like a port can have multiple devices on it (e.g. emaswitch00 port A2 appears to have 3 devices).  This might just be the conference rooms, but it is unclear, maybe Scott could give us a better idea.  In the case of multiple devices on a single port I am assuming that the port would just appear more than once in the port array? e.g. if we were sharing a cubicle:
...
"ports": [ 
    {"A1":{"firstName":"Ryan"...}},
    {"A1":{"firstName":"Mike"...}}
]
...

**Comment by raserva** [comment]
@mgriner -

You can do arrays like that in json, the brackets should be fine.

Also- we need to discuss how to handle it, but my intuition would be that
if multiple people are on the same port we should just return the latest
connected

**Comment by raserva** [comment]
done
